package com.vanniktech.music.mp3

internal val albumYearly = setOf(
  "ADE",
  "Big Burn Festival",
  "Bluetenzauber Open Air",
  "Bucht der Traeumer Festival",
  "Burning Man",
  "Container Love Festival",
  "DIGITAL DGTL",
  "Feel Festival",
  "Fusion",
  "Garbicz Festival",
  "Hoppla Festival",
  "Island Festival",
  "Loveland Festival",
  "Melodays",
  "Melt",
  "Nature One",
  "Playground",
  "Pleinvrees Festival",
  "Ploetzlich am Meer Festival",
  "Rainbow Serpant Festival",
  "Sa Terza Metari Festival",
  "Skyland",
  "Springfestival Graz",
  "Strawberry Fields Festival",
  "The BPM Festival",
  "Time Warp",
  "Fairground Festival",
  "Tomorrowland",
  "Wilde Moehre Festival",
  "Zugvøgel Festival",
  "camp cosmic",
  "Фузион",
)
