package com.vanniktech.music.mp3

internal val albumsWithTracks = setOf(
  "Smile This Mixtape",
  "NWS PODCAST",
  "Something Slow",
  "rāga",
  "BeYond",
  "KataHaifisch Podcast",
  "Thomas Youtube Mix",
  "deep story",
  "PA Elements",
  "Pearls & Sencha",
  "Rooftop Sessions",
  "EINPODCAST",
  "GWT Podcast",
  "TAECHNOPOD",
  "Desert Hearts",
  "Geisha Art Music Dance Culture",
  "mellowcast",
  "ElectriX Podcast",
  "Set Of The Day Podcast",
  "8dayCast",
  "Sunset Grooves Podcast",
  "L.E.T. Podcast",
  "Short Circuit",
  "Amsterdam Music Sessions",
  "Deep-Bazar Podcast",
  "Eduard Aldente",
  "Select Cuts",
  "Melodic Diggers",
  "Neomusic Podcast",
  "Witchtape",
  "Traumcast",
  "HS",
  "DGTL Podcast",
  "Seasidetrip",
  "soundgecloud",
  "Templecast",
  "Wuza Waves",
  "My Tribute Mixtape Series",
  "Deep Session",
  "Deep & Sexy Podcast",
  "Raus aus den Federn",
  "Ki Cast",
  "Music Is The Light",
  "Introduction",
  "Dilate Podcast",
  "zero day mix",
  "Watergate Podcast",
  "Tsugi Podcast",
  "KOMPAKT PODCAST",
  "Spectrum Nights",
  "ARIES Podcast",
  "DHA Mixtape",
  "chameleon",
  "Deep Afterhour",
  "XLR8R Podcast",
  "BEATZCAST",
  "LACUNACAST",
  "Parquet Recordings",
  "NES",
  "The Karismatik Podkast",
  "PLAYY Mix",
  "PTK",
  "Sweet Mixtape",
  "Faultierdisko",
  "Undermind Podcast",
  "Slomosensual",
  "Walk in the woods",
  "Octo Friends",
  "deep & smooth",
  "Disfruta Ahora Sunset Sessions",
  "Volt Podcast",
  "SVT Podcast",
  "parallel visions radio",
  "Electroniquement'Vôtre",
  "Steyoyoke Black Podcast",
  "Deep House Amsterdam Subjekt Podcast",
  "down.cast",
  "Systematic Session",
  "The Anjunadeep Edition",
  "Cloudbreak Records",
  "The Space Between",
  "beatverliebt",
  "FUKLACAST",
  "Solsticecast",
  "Flow Sessions",
  "SMALLCAST",
  "Groove Podcast",
  "VIBRATIONS EP",
  "Herzschlag",
  "Schleichcast",
  "Heimlich Podcast",
  "Alter Ego Podcast",
  "LIQUID YOUTH",
  "surfaces Podcast",
  "Melodic Diggers",
  "Rave Radio Episode",
  "Jeden Tag ein Set Podcast",
  "Transitions Guestmix",
  "Melodic Therapy",
  "microcastle podcast",
  "Rebirth of Spring",
  "Radikon Radio",
  "MIX",
  "Influenza Podcast",
  "Monaberry Podberry",
  "Getting Deeper Podcast",
  "GENAU Podcast",
  "Don't Forget The Moon",
  "sunrise session",
  "trndmsk Podcast",
  "trndmsk Future Stars",
  "Bedroom Sessions",
  "LBCAST",
  "Sintope Radio Show",
  "Introspectives",
  "Sincopat Podcast",
  "Pleinvrees Podcast",
  "Undermind Podcast",
  "Aplethora Radio",
  "Nomad Jam Session",
  "UCR",
  "Tonspur",
  "Global Transmission",
  "The Series",
  "The Boom Room",
  "Parquet Mixtape",
  "Afterlife Voyage",
  "Places Podcast",
  "Escultura",
  "Mousikē",
  "Igelkarussell",
  "metanoia RHYTHM",
  "Montagssorbet",
  "HOW I MET THE BASS",
  "Balance Selections",
  "BergWacht Kassetten",
  "Soulful Techno",
  "DAYS like NIGHTS",
  "MELODIC DEEP IN DEPTH PODCAST",
  "ANAPODCAST",
  "Sekay Audio Stories",
  "unu City Tape",
  "Desert Hut Podcast Series",
  "FACT mix",
  "FWD",
  "Frau Blau Radio",
  "John Digweed's Transitions",
  "Mezcla",
  "KLANGWELT",
  "Mystic Cast",
  "NRR",
  "Ninitie Mix",
  "Podcast M.D.H.",
  "Resident Advisor Podcast",
  "Soulfooled Podcast",
  "brfocast",
  "Circoloco Radio",
  "Tronic Podcast",
  "Warm Up Podcast",
  "werliebt Podcast",
  "Crossfrontier Audio Podcasts",
  "Steyoyoke Radioshow",
  "Soundwall Podcast",
  "Click Records Podcast",
  "Verboten Transmissions Podcast",
  "Crossfrontier Audio Podcast",
  "Cercle Story",
  "Heal Play Love Podcast",
  "SEKOIA Podcast",
  "BigFM Podcast",
  "When We Dip",
  "ZEROCAST",
  "Cast",
  "Headliner Series",
  "Wildwood Podcast Series",
  "Sekay Audio Stories",
  "Melodic Mixtape",
  "Radio Hommage",
  "Canopy Sounds",
  "DJ LAB",
  "Noisily Podcast",
  "Suruba Podcast",
  "Slow Playlist",
  "TRAUMWERK Podcast",
  "Serenity Heartbeat Podcast",
  "Afterhour Sounds Podcast",
  "More Morano",
  "Trip",
  "Invite's Choice Podcast",
  "NXT",
  "Colourizon",
  "Calm",
  "BDS Radioshow",
  "Deep Klassified Podcast",
  "Deepist Podcast",
  "Motek Podcast",
  "Bleep Mix",
  "PODCAST - SERIES",
  "Dekmantel Podcast",
  "Caduceus Podcast",
  "Metamorph Podcast",
  "Behind LOKD Doors",
  "Bespoke Musik Radio",
  "Smoke Machine Podcast",
  "replaycast",
  "Bootshaus Exclusive Podcast",
  "Perspektives",
  "Flow Music Podcast",
  "MietzHouse Podcast",
  "Switch 2017",
  "Tal der Verwirrung",
  "SLCTS",
  "Toys Mix",
  "LIEBE",
  "EG",
  "MONO.NOISE.TAPE",
  "United We Stream Podcast",
  "Spectrum Radio",
  "isolatedmix",
  "Fitcast",
  "Ninitie Mix",
  "EXOPLANETS",
  "Ideal Podcast",
  "LUSH CAST",
  "Crossfrontier Audio Podcasts",
  "GLYK",
  "Einmusika Podcast",
  "Club Autonomica in the mix Podcast",
  "raga",
  "Serafin Sinfonia",
)
