package com.vanniktech.music.mp3

internal val albumsWithTracks = setOf(
  "Smile This Mixtape",
  "NWS PODCAST",
  "Something Slow",
  "KataHaifisch Podcast",
  "Thomas Youtube Mix",
  "deep story",
  "PA Elements",
  "Pearls & Sencha",
  "EINPODCAST",
  "Set Of The Day Podcast",
  "8dayCast",
  "L.E.T. Podcast",
  "Amsterdam Music Sessions",
  "Select Cuts",
  "Traumcast",
  "DGTL Podcast",
  "soundgecloud",
  "Deep & Sexy Podcast",
  "Ki Cast",
  "Introduction",
  "Dilate Podcast",
  "zero day mix",
  "Watergate Podcast",
  "Tsugi Podcast",
  "KOMPAKT PODCAST",
  "Spectrum Nights",
  "ARIES Podcast",
  "DHA Mixtape",
  "chameleon",
  "Deep Afterhour",
  "XLR8R Podcast",
  "BEATZCAST",
  "Parquet Recordings",
  "NES",
  "The Karismatik Podkast",
  "PTK",
  "Sweet Mixtape",
  "Undermind Podcast",
  "Walk in the woods",
  "Volt Podcast",
  "SVT Podcast",
  "Steyoyoke Black Podcast",
  "Deep House Amsterdam Subjekt Podcast",
  "down.cast",
  "Systematic Session",
  "The Anjunadeep Edition",
  "Cloudbreak Records",
  "The Space Between",
  "beatverliebt",
  "FUKLACAST",
  "Solsticecast",
  "Flow Sessions",
  "SMALLCAST",
  "Groove Podcast",
  "VIBRATIONS EP",
  "Herzschlag",
  "Heimlich Podcasts",
  "Alter Ego Podcast",
  "LIQUID YOUTH",
  "surfaces Podcast",
  "Melodic Diggers",
  "Rave Radio Episode",
  "Jeden Tag ein Set Podcast",
  "Transitions Guestmix",
  "Melodic Therapy",
  "microcastle podcast",
  "Rebirth of Spring",
  "Radikon Radio",
  "MIX",
  "Influenza Podcast",
  "Monaberry Podberry",
  "Getting Deeper Podcast",
  "GENAU Podcast",
  "Don't Forget The Moon",
  "Calm. Sleep. - Moby",
  "sunrise session",
  "trndmsk Podcast",
  "down.cast",
  "trndmsk Future Stars",
  "LBCAST",
  "Sintope Radio Show",
  "Introspectives",
  "Sincopat Podcast",
  "Pleinvrees Podcast",
  "Aplethora Radio",
  "Nomad Jam Session",
  "UCR",
  "Tonspur",
  "Global Transmission",
  "The Series",
  "The Boom Room",
  "Parquet Mixtape",
  "Afterlife Voyage",
  "Places Podcast",
  "metanoia RHYTHM",
  "Montagssorbet",
  "HOW I MET THE BASS",
  "Balance Selections",
  "BergWacht Kassetten",
  "Soulful Techno",
  "DAYS like NIGHTS",
  "MELODIC DEEP IN DEPTH PODCAST",
  "ANAPODCAST",
  "Sekay Audio Stories",
  "unu City Tape",
  "Desert Hut Podcast Series",
  "FACT mix",
  "FWD",
  "Frau Blau Radio",
  "John Digweed's Transitions",
  "Mezcla",
  "KLANGWELT",
  "Mystic Cast",
  "NRR",
  "Ninitie Mix",
  "Podcast M.D.H.",
  "Resident Advisor Podcast",
  "Soulfooled Podcast",
  "brfocast",
  "Circoloco Radio",
  "Tronic Podcast",
  "Warm Up Podcast",
  "werliebt Podcast",
  "Crossfrontier Audio Podcasts",
  "Steyoyoke Radioshow",
  "Soundwall Podcast",
  "Click Records Podcast",
  "Verboten Transmissions Podcast",
  "Crossfrontier Audio Podcast",
  "Cercle Story",
  "Heal Play Love Podcast",
  "SEKOIA Podcast",
  "BigFM Podcast",
  "When We Dip",
  "ZEROCAST",
  "Headliner Series",
  "Wildwood Podcast Series",
  "Sekay Audio Stories",
  "Melodic Mixtape",
  "Radio Hommage",
  "Canopy Sounds",
  "DJ LAB",
  "Noisily Podcast",
  "Suruba Podcast",
  "Slow Playlist",
  "TRAUMWERK Podcast",
  "Serenity Heartbeat Podcast",
  "Afterhour Sounds Podcast",
  "More Morano",
  "Trip",
  "Invite's Choice Podcast",
  "NXT",
  "Colourizon",
  "Calm. Sleep.",
  "BDS Radioshow",
  "Deep Klassified Podcast",
  "Deepist Podcast",
  "Motek Podcast",
  "Bleep Mix",
  "PODCAST - SERIES",
  "Dekmantel Podcast",
  "Caduceus Podcast",
  "Metamorph Podcast",
  "Behind LOKD Doors",
  "Bespoke Musik Radio",
  "Smoke Machine Podcast",
  "replaycast",
  "Bootshaus Exclusive Podcast",
  "Perspektives",
  "Flow Music Podcast",
  "MietzHouse Podcast",
  "Switch 2017",
  "Tal der Verwirrung",
  "SLCTS",
  "Toys Mix",
  "LIEBE",
  "EG",
  "MONO.NOISE.TAPE",
  "United We Stream Podcast",
  "Spectrum Radio",
  "isolatedmix",
  "Fitcast",
  "Ninitie Mix",
  "EXOPLANETS",
  "Ideal Podcast",
  "LUSH CAST",
  "Crossfrontier Audio Podcasts",
  "GLYK",
  "Einmusika Podcast",
  "Club Autonomica in the mix Podcast",
)
