package com.vanniktech.music.mp3

internal val albumsWithoutTracks = setOf(
  "2DIY4 Exposé",
  "Radio 538",
  "27-4 Rayk's Session",
  "6 Jahre Jeden Tag ein Set",
  "Atlant Radio Show",
  "BergWacht",
  "LDS",
  "Expect No Borders",
  "Boiler Room",
  "Cercle",
  "Kater Blau",
  "RAWK",
  "Data Transmission",
  "Diynamic Radio Show",
  "Einmusika Radio Show",
  "Essential Mix",
  "Herzfrequenz",
  "Hyperharmonic",
  "Incroyable Music Radioshow",
  "Manual Movement",
  "Moodmusic Radioshow",
  "OpenLab",
  "Oaxaca Mexico",
  "Plattenkoffer",
  "Pleinvrees on Tour",
  "Pleinvrees 010",
  "Sisyphos",
  "Travel Without Moving",
  "Unity Live",
  "WUITW",
  "Warm Up London",
  "Watergate Berlin",
  "driving slowly",
  "komm schon Alter - das Festival",
  "komm schon Alter VII podcast",
  "My",
  "magical forest",
  "Magician On Duty",
  // Our own 'albums'.
  "Im Strom der Zeit",
  "Hardtrance",
  "Others",
  "Progressive",
  "Techno Fresse",
)
