package com.vanniktech.music.mp3

internal val genres = setOf(
  "Ballern [Classics]",
  "Ballern [Gezerre]",
  "Ballern [Hypno]",
  "Ballern",
  "Chillig",
  "Chillout",
  "Classics",
  "Different",
  "Downtempo",
  "Druck",
  "Flauschig",
  "Melodic",
  "Mindfuck Hypno",
  "Neo Melodic",
  "Oldschool [Ballern]",
  "Oldschool [Chillig]",
  "Oldschool [Groovy]",
  "Oldschool [Gute Laune]",
  "Oldschool [Melodic]",
  "Oldschool [Seelenfutter]",
  "Oldschool [Warmup]",
  "Oldschool",
  "Ploppig",
  "Seelenfutter",
  "Spacy Indian",
  "Techno",
  "Uncategorized",
  "Warmup",
)
